name: Check Inactive Users

on:
  schedule:
    - cron: '50 21 * * *' # Runs every day at midnight

jobs:
  check-inactive-users:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run PowerShell script
        env:
          CLIENT: ${{ secrets.AZURE_AD_CLIENT_ID }}
          SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          TENANT: ${{ secrets.AZURE_AD_TENANT_ID }}
          GROUP_OBJECT_ID: '6c1b5bfa-a803-454a-8432-db74de88c01e'
          TEAM_WEBHOOK_URL: ${{ secrets.TEAM_WEBHOOK_URL }}
        run: |
          $clientId = $env:AZURE_AD_CLIENT_ID
          $clientSecret = $env:AZURE_AD_CLIENT_SECRET
          $tenantId = $env:AZURE_AD_TENANT_ID
          $groupObjectId = $env:GROUP_OBJECT_ID
          $emailFrom = $env:EMAIL_FROM
          $emailTo = $env:EMAIL_TO
