name: Check Inactive Users

on:
  schedule:
    - cron: '15 22 * * *' # Runs every day at midnight
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  check-inactive-users:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install required modules
        run: |
          Install-Module -Name MSAL.PS -Force -Scope CurrentUser -Verbose
          Install-Module -Name AzureAD -Force -Scope CurrentUser -Verbose

      - name: Set Execution Policy
        run: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser

      - name: Run PowerShell script
        env:
          CLIENT: ${{ secrets.CLIENT }}
          SECRET: ${{ secrets.SECRET }}
          TENANT: ${{ secrets.TENANT }}
          GROUP_OBJECT_ID: '6c1b5bfa-a803-454a-8432-db74de88c01e'
          TEAM_WEBHOOK_URL: ${{ secrets.TEAM_WEBHOOK_URL }}
        shell: powershell
        run: |
          .\inactiveusers.ps1
