name: Check Inactive Users on Ubuntu

on:
  schedule:
    - cron: '15 22 * * *' # Runs every day at 22:15 UTC
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  check-inactive-users:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install Microsoft Graph PowerShell SDK
        run: |
          Install-Module -Name Microsoft.Graph -Force -Scope CurrentUser -Verbose
        shell: pwsh

      - name: Run PowerShell script
        env:
          CLIENT: ${{ secrets.CLIENT }}
          SECRET: ${{ secrets.SECRET }}
          TENANT: ${{ secrets.TENANT }}
          GROUP_OBJECT_ID: ${{ secrets.GROUP_OBJECT_ID }}
          TEAM_WEBHOOK_URL: ${{ secrets.TEAM_WEBHOOK_URL }}
        run: |
          pwsh -File ./inactiveusers.ps1
        shell: pwsh
