name: Check Inactive Users

on:
  schedule:
    - cron: '15 22 * * *' # Runs every day at midnight
  watch:
    types: [started]

jobs:
  check-inactive-users:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run PowerShell script
        env:
          CLIENT: ${{ secrets.AZURE_AD_CLIENT_ID }}
          SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          TENANT: ${{ secrets.AZURE_AD_TENANT_ID }}
          GROUP_OBJECT_ID: '6c1b5bfa-a803-454a-8432-db74de88c01e'
          TEAM_WEBHOOK_URL: ${{ secrets.TEAM_WEBHOOK_URL }}
        run: |
          $clientId = $env:CLIENT
          $clientSecret = $env:SECRET
          $tenantId = $env:TENANT
          $groupObjectId = $env:GROUP_OBJECT_ID
          $teamsWebhookUrl = $env:TEAM_WEBHOOK_URL
